### ISSUE TITLE
ERROR - Failed to start session successfully

### ISSUE THREAD

**Issue by kcconnor** [wnielson/Plex-Remote-Transcoder#4]
Environment:

Plex Media Server 9.14.4 (web interface version 2.4.37) running on Synology DS214play (Intel Atom 1.6ghz, x86_64, Synology DSM 5.2).  IP = 192.168.1.254

Ubuntu 14.04LTS virtual machine running inside Oracle VirtualBox, fresh load for this project.  Added python_setuptools, git, sshd.  IP = 192.168.1.253

SSH is working correctly from PMS to PRT virtual box.  I can get a shell, no password prompt after getting the public key pushed correctly.

I've got my NFS shares set up, and have even over-shared, allowing RW access rather than RO access for several of them.

My .prt.conf file is stock and unmolested from defaults.  The portion pertaining to server configs is as follows:

---

```
"path_script": null, 
"ipaddress": "192.168.1.254", 
"servers": {
    "192.168.1.253": {
        "port": "22", 
        "user": "plex"
    }
}
```

---

When I attempt to play a file in transcoded format, my prt.log file is as follows:

---

2015-12-17 00:23:39,299 - prt - INFO - Host with minimum load is '192.168.1.253'
2015-12-17 00:23:39,300 - prt - INFO - Using transcode host '192.168.1.253'
## 2015-12-17 00:23:39,300 - prt - INFO - Launching transcode_remote with args ['ssh', u'plex@192.168.1.253', '-p', u'22', u'export LD_LIBRARY_PATH=/usr/lib/plexmediaserver:$LD_LIBRARY_PATH;cd /var/packages/plexmediaserver/Resources;prt_local ']

And my "Plex Media Server.log" file looks like this:

---

Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - MDE: analyzing media item 11975
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - MDE: E06 - Tweek x Craig: Direct Play is disabled
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - MDE: E06 - Tweek x Craig: media must be transcoded in order to use the dash protocol
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - E06 - Tweek x Craig - video.width limitation applies: 720 > 420
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - E06 - Tweek x Craig - video.width limitation applies: 720 > 420
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - MDE: E06 - Tweek x Craig: no remuxable profile found, so video stream will be transcoded
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - E06 - Tweek x Craig - video.width limitation applies: 720 > 420
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - MDE: computed resolution bounding box of 420x236.
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - Scaled up video bitrate to 652Kbps based on 1.500000x fudge factor.
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - Scaled maximum bitrate for resolution reduction to 222Kbps.
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - MDE: E06 - Tweek x Craig: selected media 0 / 11975
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - Found session GUID of 3lney02ctxr in session start.
Dec 16, 2015 23:53:31 [0xab335b70] VERBOSE - [IDLE] Adding (0->1) work item transcoder - 3lney02ctxr
Dec 16, 2015 23:53:31 [0xab335b70] VERBOSE - [IDLE] Server is now active
Dec 16, 2015 23:53:31 [0xab335b70] VERBOSE - [IDLE] \* transcoder - 3lney02ctxr - 1 active item(s)
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - Cleaning directory for session 3lney02ctxr ()
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - Starting a transcode session 3lney02ctxr at offset -1.0 (state=2)
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - [Universal] Using local file path instead of URL: /volume1/Media/Video/South Park/South.Park.S19E06.INTERNAL.HDTV.x264-KILLERS.mp4
Dec 16, 2015 23:53:31 [0xab335b70] VERBOSE - Sufficient disk space: 94568459 bytes source file, 2948734640128 bytes capacity, 540472107008 bytes available on /volume1/Media/BitTorrent/
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - TranscodeJobManager: [Throttled] onTranscodeSessionStarted: 3lney02ctxr
Dec 16, 2015 23:53:31 [0xab335b70] DEBUG - Job running: XDG_CACHE_HOME='/volume1/Plex/Library/Application Support/Plex Media Server/Cache/' XDG_DATA_HOME='/volume1/@appstore/Plex Media Server/Resources/' '/volume1/@appstore/Plex Media Server/Resources/Plex New Transcoder' '-i' '/volume1/Media/Video/South Park/South.Park.S19E06.INTERNAL.HDTV.x264-KILLERS.mp4' '-filter_complex' '[0:#0x02]scale=w=min(420\,iw):h=min(236\,ih):force_original_aspect_ratio=decrease[0]' '-map' '[0]' '-codec:0' 'libx264' '-crf:0' '22' '-pix_fmt:0' 'yuv420p' '-maxrate:0' '222k' '-bufsize:0' '444k' '-preset:0' 'veryfast' '-x264opts' 'cabac=0:8x8dct=1:bframes=0:subme=2:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none:cabac=0' '-force_key_frames:0' 'expr:gte(t,0+n_forced*8)' '-map' '0:#0x01' '-codec:1' 'copy' '-copypriorss:1' '0' '-f' 'dash' '-use_timeline' '0' '-min_seg_duration' '8000000' '-skip_to_segment' '1' '-time_delta' '0.0625' '-avoid_negative_ts' 'disabled' '-map_metadata' '-1' 'dash' '-start_at_zero' '-copyts' '-vsync' 'cfr' '-y' '-nostats' '-loglevel' 'quiet' '-loglevel_plex' 'error' '-progressurl' 'http://127.0.0.1:32400/video/:/transcode/session/3lney02ctxr/progress'
Dec 16, 2015 23:53:33 [0xab335b70] ERROR - Failed to start session successfully.
Dec 16, 2015 23:53:33 [0xab335b70] DEBUG - Cleaning directory for session 3lney02ctxr (/volume1/Media/BitTorrent/plex-transcode-3lney02ctxr-db79a18f-91e3-4250-93ff-4428cd5ab429)
Dec 16, 2015 23:53:33 [0xab335b70] VERBOSE - [IDLE] Removing (1->0) work item transcoder - 3lney02ctxr
## Dec 16, 2015 23:53:33 [0xab335b70] VERBOSE - [IDLE] Server is now idle

When I SSH into the PMS and run the ./plex_transcoder binary with no arguments, I get a list of ffmpeg options.  But when I run the "Plex New Transcoder" binary in the same directory with no arugments, I get the following:

---

/volume1/@appstore/Plex Media Server/Resources $ ./Plex\ New\ Transcoder 
Traceback (most recent call last):
  File "/usr/local/bin/prt_local", line 9, in <module>
    load_entry_point('prt==0.2.0', 'console_scripts', 'prt_local')()
  File "build/bdist.linux-x86_64/egg/prt.py", line 167, in transcode_local
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
## OSError: [Errno 2] No such file or directory

I'm trying to be as self-service with this as possible, but I cannot figure out exactly how the "Plex New Transcoder" is building a statement to execute from what Plex sends it.  I've even gone so far as to install bash on my PMS and alter my plex account to use bash by default, giving me a .bash_history file in its home directory... but that's empty.

I'm guessing this is environmental, but I'm not sure where to look.  Any help would be appreciated.

**Comment by kcconnor** [comment]
Nevermind, close this issue.  I see the problem.

The newly renamed plex_transcoder cannot execute from the Ubuntu box because it's trying to execute a binary compiled to run in the Synology environment.  I assumed that the DS214play's Atom processor was close enough to the Ubuntu amd64 environment but I guess not.

I'll be keeping myDS214play as a NAS, exporting my media share over NFS to protect it on RAID, and implementing a little micro-PC like the Intel NUC and running Plex from it.  If I find I need increased transcoder power then I'll chain a second NUC using the remote transcoder.

Thanks for a great product.
